language: ruby
rvm:
- 2.2.0
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
deploy:
  provider: heroku
  api_key:
    secure: Khw7fSLD4gtrGB31c9KMlDtQeLw0lZ1OifSa2aj6gE8DjdUu1iIpNnIkl/32j6/qPhX0jLsU/STjonKxQiUyvIvmhB+FbJx+AFVSjm8BSeXD7enBojtTgzx+jLYGXFJUXnxzYKz3++OT/XbcnKExb0ehqW3DG5vAZMAj3a4fKyY=
  run: rake db:migrate
  app: event-ticketing
  on:
    repo: avrj/eventTicketing
